### ISSUE TITLE
Sreen Issue

### ISSUE THREAD

**Issue by Eshatos** [audiophonics/RaspDacMinilcd#1]
Hello,
I have a problem with my RaspDAC Mini LCD. I installed Moode 8 and then did everything as described on this GitHub page, https://github.com/audiophonics/RaspDacMinilcd
Unfortunately, I don't get a proper cover view screen. The screen looks permanently like on the picture attached.

<a href="https://ibb.co/VxHgLT5"><img src="https://i.ibb.co/VxHgLT5/photo1648545512.jpg" alt="photo1648545512" border="0" /></a>

I tried all the troubleshooting as described on GitHub without any help.
Can you help me somehow?
Greetings
Eshatos

**Comment by audiophonics** [comment]
Hello, 

I am aware the display has issues in moOde 8. It has something to do with the way I handle the PHP session.
 Some data are not flowing as they did anymore and the display script is confused about this.

Except if you can code in PHP / javascript / bash there is nothing you can do except waiting. 
However this should not take me more than a couple days before I can release a fix. 

I will give you an update here when I have a solution ready.

**Comment by audiophonics** [comment]
Hello, 
Sorry it took that long. I detected a couple more things that were not running nicely and I got carried away into pushing a big update that I wanted to do for a while.

Can you try following those instructions : https://github.com/audiophonics/RaspDacMinilcd/tree/moode on a fresh install ?

**Comment by Eshatos** [comment]
Hey,

this worked flawlessly, thank very much for your great work!

Update: Sadly now that I've added my library I don't get the cover art shown  

![photo1650708197](https://user-images.githubusercontent.com/7727160/164889929-41364455-3548-4fec-ad5b-ea372c5e6684.jpeg)

**Comment by Eshatos** [comment]
Hello, sadly in only worked for the radio stations, after I've now added my library I get screen tethering during playback without showing the album art

https://user-images.githubusercontent.com/7727160/164889675-9bf14fb2-9a9a-46d1-b166-4fc39e6ed65d.mp4

.

**Comment by audiophonics** [comment]
Well you were to quick to thank me it seem.

Can you retry the exact same procedure? The library should be resolving the path to remote cover pictures correctly (I had shamefully forgotten a "/" somewhere).

There is no need to format / reflash the SD card, configuration should be updated accordingly. 
I also told the graphics renderer to automatically stop the localui in case both were enabled at the same time.

Tell me if everything is working as expected on your side.

**Comment by Eshatos** [comment]
Hey,

your last update did the thing, thank u a lot! Let me know by pm if I can somehow tip you for your great work!

**Comment by audiophonics** [comment]
Thank you but that won't be necessary. 

If you **really** want to do a gesture to show appreciation, I would suggest saying a couple nice words on Trustpilot. I can use that as leverage to show my coworkers that time spent on upgrading & maintaining software is time well spent.

Otherwise just enjoy the RaspDacMini and let me know if anything goes wrong after an update. 

I'll leave the issue open for a short while in case something else happens.
